# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
---
version: 2
project_name: yatto

builds:
  - ldflags:
      - "-s -w"
      - "-extldflags=-zrelro"
      - "-extldflags=-znow"
    env:
      - "CGO_ENABLED=0"
      - "GO111MODULE=on"
      - "GOFLAGS=-mod=readonly -trimpath"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^build:"

signs:
  - cmd: cosign
    signature: "${artifact}.sig.bundle"
    args:
      - sign-blob
      - --bundle=${signature}
      - --yes
      - "${artifact}"
    artifacts: checksum

release:
  github:
    owner: handlebargh
    name: yatto
  prerelease: auto
  make_latest: true

homebrew_casks:
  - name: yatto
    repository:
      owner: handlebargh
      name: homebrew-yatto
      branch: main
    homepage: https://github.com/handlebargh/yatto
    description: Interactive VCS-based todo-list for the command-line
    license: MIT
    url:
      template: "https://github.com/handlebargh/yatto/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: github.com/handlebargh/yatto/releases/download
    artifact: "yatto_Darwin_*.tar.gz"
    binaries:
      - yatto

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/handlebargh/yatto
    description: |-
      Interactive VCS-based todo-list for the command-line
    maintainer: Benedikt Zumtobel <benedikt at zumtobel dot dev>
    license: MIT
    bindir: /usr/bin
    section: utils
    mtime: "{{ .CommitDate }}"
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/yatto/copyright
        file_info:
          mode: 0644
          mtime: "{{ .CommitDate }}"
    recommends:
      - git
    formats:
      - apk
      - deb
      - rpm
    rpm:
      signature:
        key_file: "{{ .Env.GPG_KEY_PATH }}"
    deb:
      signature:
        key_file: "{{ .Env.GPG_KEY_PATH }}"
        type: origin

scoop:
  - name: yatto
    repository:
      owner: handlebargh
      name: scoop-bucket
      branch: main
    homepage: https://github.com/handlebargh/yatto
    description: Interactive VCS-based todo-list for the command-line
    license: MIT