# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
---
version: 2
project_name: yatto

source:
  enabled: true

builds:
  - id: yatto
    binary: yatto
    ldflags:
      - "-s -w"
      - "-buildid="
      - '{{- if eq .Os "linux" }}-extldflags=-static-pie{{- end }}'
      - '{{- if eq .Os "linux" }}-extldflags=-zrelro{{- end }}'
      - '{{- if eq .Os "linux" }}-extldflags=-znow{{- end }}'
    env:
      - "CGO_ENABLED=0"
    flags:
      - "-trimpath"
      - "-mod=readonly"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: yatto
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^build:"

signs:
  - cmd: cosign
    signature: "${artifact}.sig.bundle"
    args:
      - sign-blob
      - --bundle=${signature}
      - --yes
      - "${artifact}"
    artifacts: checksum

release:
  github:
    owner: handlebargh
    name: yatto
  draft: true
  make_latest: true
  extra_files:
    - glob: ./yatto_signing_pubkey.gpg

brews:
  - name: yatto
    repository:
      owner: handlebargh
      name: homebrew-yatto
      branch: main
      token: "{{ .Env.PACKAGE_UPDATE_TOKEN }}"
    homepage: https://github.com/handlebargh/yatto
    description: Interactive VCS-based todo-list for the command-line
    license: MIT
    caveats: |
      yatto requires either Git or Jujutsu (jj) to be installed and available in your PATH.
      You can install them with:
        brew install git
      or
        brew install jj
    test: |
      system "#{bin}/yatto", "version"

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/handlebargh/yatto
    description: |-
      Interactive VCS-based todo-list for the command-line
    maintainer: Benedikt Zumtobel <github at zmtbl dot at>
    license: MIT
    bindir: /usr/bin
    section: utils
    mtime: "{{ .CommitDate }}"
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/yatto/copyright
        file_info:
          mode: 0644
          mtime: "{{ .CommitDate }}"
    recommends:
      - git
    formats:
      - apk
      - deb
      - rpm
    rpm:
      signature:
        key_file: "{{ .Env.GPG_KEY_PATH }}"
    deb:
      signature:
        key_file: "{{ .Env.GPG_KEY_PATH }}"
        type: origin

scoops:
  - name: yatto
    repository:
      owner: handlebargh
      name: scoop-bucket
      branch: main
      token: "{{ .Env.PACKAGE_UPDATE_TOKEN }}"
    homepage: https://github.com/handlebargh/yatto
    description: Interactive VCS-based todo-list for the command-line
    license: MIT

aur_sources:
  - name: yatto
    homepage: "https://github.com/handlebargh/yatto"
    description: "Interactive VCS-based todo-list for the command-line"
    maintainers:
      - "Benedikt Zumtobel <benedikt at zumtobel dot dev>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/yatto.git"
    provides: []
    conflicts: []
    depends:
      - git
    prepare: |-
      go mod download
    build: |-
      export CGO_ENABLED=0
      export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
      go build \
        -ldflags "-s -w -linkmode=external -extldflags=-Wl,-z,relro,-z,now -buildid=" \
        -o "${pkgname}"
      chmod +x "${pkgname}"
      for shell in bash fish zsh; do
        ./"${pkgname}" completion "$shell" > "${shell}-completion"
      done
    package: |-
      install -Dm755 "${pkgname}" "${pkgdir}/usr/bin/${pkgname}"
      install -Dm644 bash-completion "${pkgdir}/usr/share/bash-completion/completions/${pkgname}"
      install -Dm644 fish-completion "${pkgdir}/usr/share/fish/vendor_completions.d/${pkgname}.fish"
      install -Dm644 zsh-completion "${pkgdir}/usr/share/zsh/site-functions/_${pkgname}"
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
