[assignee]
## Whether to show assignee in task list
show = false

## Whether to show assignee when running yatto print
show_printer = false

[author]
## Whether to show author in task list
show = false

## Whether to show author when running yatto print
show_printer = false

## The colors used throughout the application
## If your terminal does not support true color
## you will have to use ANSI 16 or ANSI 256 colors instead
[colors]
badge_text_dark = "#000000"
badge_text_light = "#000000"
blue_dark = "#1e90ff"
blue_light = "#1e90ff"
green_dark = "#02BF87"
green_light = "#02BA84"
indigo_dark = "#7571F9"
indigo_light = "#5A56E0"
orange_dark = "#FFA336"
orange_light = "#FFB733"
red_dark = "#FE5F86"
red_light = "#FE5F86"
vividred_dark = "#FE134D"
vividred_light = "#FE134D"
yellow_dark = "#CCCC00"
yellow_light = "#CCCC00"

[colors.form]
## The theme used in the project/task form
##
## Available values are:
##
## - Charm
## - Dracula
## - Catppuccin
## - Base16
## - Base
theme = "Base16"

[vcs]
## The VCS used for backend operation
## **DO NOT CHANGE AFTER INITIALIZATION**
## allowed values: "git", "jj"
backend = "git"

[git]
## Name of the git branch used by yatto
default_branch = "main"

[git.remote]
## Whether to enable a remote repository
enable = false

## Name of the git remote
name = "origin"

## URL of the git remote
url = "git@github:<username>/<repo>.git"

[jj]
## Name of the jj bookmark tracked by yatto
## (falsely called branch, things don’t always go as planned)
default_branch = "main"

[jj.remote]
## Whether to enable a remote repository
enable = false

## Whether to colocate the Jujutsu repository
colocate = false

## Name of the jj/git remote
name = "origin"

## URL of the jj/git remote
url = "git@github:<username>/<repo>.git"

[storage]
## Where to locate the storage directory.
##
## Replace with your actual home directory
## or any other path you'd like to use.
path = "/home/<me>/.yatto"
