Output demo.gif

Require yatto

Set Shell "bash"
Set FontSize 18
Set Width 1200
Set Height 800

Type "yatto" Sleep 500ms  Enter

Sleep 2s

Enter Sleep 1s
Type "/readme" Sleep 2s
Enter
Type "e" Sleep 500ms
Enter Sleep 500ms
Enter Sleep 500ms
Type "Create a short demo to showcase the application." Sleep 500ms
Enter Sleep 500ms
Enter Sleep 500ms
Enter Sleep 500ms
Enter Sleep 3s
Type "C" Sleep 3s
Enter Sleep 2s
