---
name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cache_path: ~/go/pkg/mod
            test_command: go test -v -race -coverprofile=coverage.txt ./...
          - os: macos-latest
            cache_path: ~/go/pkg/mod
            test_command: go test -v -race ./...
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ${{ matrix.cache_path }}
          key: ${{ matrix.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: ${{ matrix.test_command }}

      - name: Upload results to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v5